#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(binding = 0) buffer VoxelGridIn {
    uint voxel_grid_in[];
};

layout(rgba32f, binding = 1) uniform image2D img_output;

void main () {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 image_size = ivec2(gl_NumWorkGroups.xy) * 8;

    vec4 color = vec4((vec2(pixel_coords) / vec2(image_size)), 0.0, 1.0);
    imageStore(img_output, pixel_coords, color);
}